spring:
  application:
    name: TemperatureProvider
server:
  port: 52449
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true