spring:
  application:
    name: CityService
server:
  port: 50618
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
city:
    service:
        cron: 0 * * * * *